/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/layouts/AdminLayout.vue')['default']
    AdminView: typeof import('./src/modules/admin/views/AdminView.vue')['default']
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginCard: typeof import('./src/modules/auth/components/LoginCard.vue')['default']
    LoginForm: typeof import('./src/modules/auth/components/LoginForm.vue')['default']
    LoginView: typeof import('./src/modules/auth/views/LoginView.vue')['default']
    MedicosView: typeof import('./src/modules/medico/views/MedicosView.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MenuProfile: typeof import('./src/components/MenuProfile.vue')['default']
    Password: typeof import('primevue/password')['default']
    RegisterForm: typeof import('./src/modules/auth/components/RegisterForm.vue')['default']
    RegisterView: typeof import('./src/modules/auth/views/RegisterView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stepper: typeof import('primevue/stepper')['default']
    StepperPanel: typeof import('primevue/stepperpanel')['default']
    VideoCallView: typeof import('./src/modules/videocall/views/VideoCallView.vue')['default']
  }
}
