/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/layouts/AdminLayout.vue')['default']
    AdminProfileView: typeof import('./src/modules/admin/views/AdminProfileView.vue')['default']
    AdminView: typeof import('./src/modules/admin/views/AdminView.vue')['default']
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/modules/auth/components/LoginForm.vue')['default']
    LoginView: typeof import('./src/modules/auth/views/LoginView.vue')['default']
    MedicosForm: typeof import('./src/modules/auth/components/MedicosForm.vue')['default']
    MedicosProfileView: typeof import('./src/modules/medico/views/MedicosProfileView.vue')['default']
    MedicosView: typeof import('./src/modules/medico/views/MedicosView.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MenuProfile: typeof import('./src/components/MenuProfile.vue')['default']
    PacienteProfileView: typeof import('./src/modules/profile/components/PacienteProfileView.vue')['default']
    PacientesForm: typeof import('./src/modules/auth/components/PacientesForm.vue')['default']
    Password: typeof import('primevue/password')['default']
    ProfileView: typeof import('./src/modules/profile/views/ProfileView.vue')['default']
    RegisterView: typeof import('./src/modules/auth/views/RegisterView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionLanding: typeof import('./src/components/SectionLanding.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Stepper: typeof import('primevue/stepper')['default']
    StepperPanel: typeof import('primevue/stepperpanel')['default']
    Textarea: typeof import('primevue/textarea')['default']
    VideoCallView: typeof import('./src/modules/videocall/views/VideoCallView.vue')['default']
    VideoWebRTC: typeof import('./src/modules/videocall/components/VideoWebRTC.vue')['default']
  }
}
