/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/layouts/AdminLayout.vue')['default']
    AdminView: typeof import('./src/modules/admin/views/AdminView.vue')['default']
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    LoginView: typeof import('./src/modules/auth/views/LoginView.vue')['default']
    MedicosView: typeof import('./src/modules/medico/views/MedicosView.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MenuProfile: typeof import('./src/components/MenuProfile.vue')['default']
    RegisterView: typeof import('./src/modules/auth/views/RegisterView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoCallView: typeof import('./src/modules/videocall/views/VideoCallView.vue')['default']
  }
}
